### ISSUE TITLE
install issue ?

### ISSUE THREAD

**Issue by chrvoigt** [nostalgia-dev/nostalgia#25]
Hi Pascal, 
great idea analyzing personal data across multiple sites ... have you got any experience with the install failure below? It might be my personal set-up ..
However, first I got a PEP517 error (googeling that I used the --no-binary option and got a 'no requirements.txt' error 

Thanks for any advice 
Chris   

++++++++
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  ld: library not found for -lstdc++
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'g++' failed with exit status 1

+++++++++++++
  ERROR: Failed building wheel for ujson
Failed to build ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly
me@Chriss ~/code/_notebooks $ 

*************

me@Chriss ~/code/_notebooks $ pip -V
pip 20.0.2 from /Users/me/miniconda3/lib/python3.7/site-packages/pip-20.0.2-py3.7.egg/pip (python 3.7)
me@Chriss ~/code/_notebooks $ pip install nostalgia --no-binary :all:
Collecting nostalgia
  Using cached nostalgia-0.1.52.tar.gz (297 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pyarrow
  Using cached pyarrow-0.16.0.tar.gz (5.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting natura
  Using cached natura-0.0.63.tar.gz (37 kB)
Collecting ujson
  Using cached ujson-2.0.1.tar.gz (7.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting ijson
  Using cached ijson-2.6.1.tar.gz (29 kB)
Requirement already satisfied: lxml in /Users/me/miniconda3/lib/python3.7/site-packages (from nostalgia) (4.4.1)
Collecting tok
  Using cached tok-0.1.14.tar.gz (5.6 kB)
Collecting metadate
  Using cached metadate-0.5.74.tar.gz (22 kB)
Requirement already satisfied: pandas in /Users/me/miniconda3/lib/python3.7/site-packages (from nostalgia) (0.25.1)
Collecting tldextract
  Using cached tldextract-2.2.2.tar.gz (63 kB)
Collecting python-dotenv
  Using cached python-dotenv-0.12.0.tar.gz (28 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cython
  Using cached Cython-0.29.15.tar.gz (2.1 MB)
Collecting tzlocal
  Using cached tzlocal-2.0.0.tar.gz (22 kB)
Collecting auto-extract
  Using cached auto_extract-0.0.8.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/me/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/00/s5zlzrps4ln6_m054vgl3_3r0000gn/T/pip-install-kohd12fm/auto-extract/setup.py'"'"'; __file__='"'"'/private/var/folders/00/s5zlzrps4ln6_m054vgl3_3r0000gn/T/pip-install-kohd12fm/auto-extract/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/00/s5zlzrps4ln6_m054vgl3_3r0000gn/T/pip-install-kohd12fm/auto-extract/pip-egg-info
         cwd: /private/var/folders/00/s5zlzrps4ln6_m054vgl3_3r0000gn/T/pip-install-kohd12fm/auto-extract/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/00/s5zlzrps4ln6_m054vgl3_3r0000gn/T/pip-install-kohd12fm/auto-extract/setup.py", line 9, in <module>
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
me@Chriss ~/code/_notebooks $

**Comment by kootenpv** [comment]
Hi Chris! Thanks a lot for reporting the bug. 

I just pushed a fix. This is a reminder we should improve our CI/CD.

Could you please try the following and see if it works for you?

    pip install -U nostalgia>=0.1.67

**Comment by chrvoigt** [comment]
all good, now I can check my heart rate over the past years .. courtesy by Samsung  ;-) 
thanks for the quick turnaround !

**Comment by kootenpv** [comment]
Thank you for checking it so quickly! Feel free to talk to us at either Slack: https://bit.ly/2Yre09N or
Discord: https://discord.gg/nJQfM2A
